# Generated by Django 5.1.3 on 2024-11-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('startyear', models.IntegerField()),
                ('endyear', models.IntegerField()),
                ('current', models.BooleanField()),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
