# Generated by Django 5.1.3 on 2024-11-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='endmonth',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='startmonth',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
