# Generated by Django 5.1.3 on 2024-11-23 22:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0002_experience_endmonth_experience_startmonth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='endmonth',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='endyear',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='startmonth',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='startyear',
        ),
        migrations.AddField(
            model_name='experience',
            name='enddate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='startdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
