# Generated by Django 5.1.3 on 2024-11-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0003_remove_experience_endmonth_remove_experience_endyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
