# Generated by Django 5.1.3 on 2024-11-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0006_experience_skills_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='notes',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='skills',
            field=models.ManyToManyField(blank=True, to='resumebuilder.skill'),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, to='resumebuilder.skill'),
        ),
    ]
