# Generated by Django 5.1.3 on 2024-11-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0007_job_link_job_notes_alter_experience_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('experiences', models.ManyToManyField(blank=True, to='resumebuilder.experience')),
                ('jobs', models.ManyToManyField(blank=True, to='resumebuilder.job')),
                ('skills', models.ManyToManyField(blank=True, to='resumebuilder.skill')),
            ],
        ),
    ]
