# Generated by Django 5.1.3 on 2024-12-03 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
