# Generated by Django 5.1.3 on 2024-12-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0011_alter_profile_experiences_alter_profile_jobs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('skills', models.ManyToManyField(blank=True, to='resumebuilder.skill')),
            ],
        ),
    ]
