# Generated by Django 5.1.3 on 2024-12-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0013_profile_portfoliopieces'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopiece',
            name='image',
            field=models.ImageField(blank=True, upload_to='portfolio_pictures'),
        ),
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
